spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: '587'
    username: ${MAIL_USERNAME:my-mail-username}
    password: ${MAIL_PASSWORD:my-mail-password}
    properties:
      mail:
        smtp:
          starttls:
            required: 'true'
          auth: 'true'
      smtp:
        starttls:
          enable: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    # Utilizar apenas pra desenvolvimento
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}